data_config = {
    'proxymode': 'localhost',
    'spmlchangelocation': 'company',
    'spmlchangetimeout': 'user',
    'spmlchangemaxfilesize': 'password',
    'northhttpsenable': 3306,
    'proxymode': 'localhost',
    'spmlchangelocation': 'company',
    'spmlchangetimeout': 'user',
    'spmlchangemaxfilesize': 'password',
    'northhttpsenable': 3306,
    'proxymode': 'localhost',
    'spmlchangelocation': 'company',
    'spmlchangetimeout': 'user',
    'defaultproxyuser': 'password',
    'inactivity_timeout': 3306,
    'connect_timeout': 'localhost',
    'northverifypeer': 'company',
    'northcertificate': 'user',
    'northprivatekey': 'password',
    'northhttpsenable': 3306,
    "connectionlimit":1,            
}